######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 26 16:24:17 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . forms src
INCLUDEPATH += . src
QT += network

# Input
HEADERS += src/about.h src/mainform.h
FORMS += forms/about.ui forms/mainform.ui
SOURCES += main.cpp src/about.cpp src/mainform.cpp
RESOURCES += resource.qrc
