######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 23 14:40:24 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . forms src
INCLUDEPATH += . src
QT += network

# Input
HEADERS += src/mainform.h src/progressform.h
FORMS += forms/mainform.ui forms/progressform.ui
SOURCES += main.cpp src/mainform.cpp src/progressform.cpp
RESOURCES += resource.qrc
